version: "3"

services:


    static:
        image: nginx
        #restart: always
        ports:
            - 80:80
        volumes: 
            - ./nginx-static/static:/usr/share/nginx/html
            - ./nginx-static/nginx.conf:/etc/nginx/nginx.conf

    