version: "3"

services:

    proxy:
        image: nginx
        #restart: always
        depends_on:
            - static
            - flask
        volumes: 
           - ./nginx-proxy/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80

    static:
        image: nginx
        #restart: always
        
        volumes: 
            - ./nginx-static/static:/usr/share/nginx/html

    flask:
        #image: nginx
        #restart: always
        build: ./flask
        ports:
            - 8080:80
        depends_on:
            - redis
    
    redis:
        image: redis:alpine
         
